is_debug: ${IS_DEBUG:-false}
listen:
  type: ${TYPE:-tcp}
  bindIP: ${BINDIP:-0.0.0.0}
  port: ${PORT:-8080}
postgresql:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  username: ${DB_USER:-postgres}
  password: ${DB_PASSWORD:-}
  database: ${DB_NAME:-db}
  pool:
    max_cons: ${MAX_CONS:-10}
    min_cons: ${MIN_CONS:-2}
    max_con_lifetime: ${MAX_CONS_LIFETIME:-5m}